### ISSUE TITLE
support py34?

### ISSUE THREAD

**Issue by ThomasWaldmann** [rixx/abbr#1]
maybe could be easily done and good for running it everywhere, except if you need the latest and greatest python features. ;)

**Comment by rixx** [comment]
I'm fairly sure that `abbr` is de-facto compatible with Python 3.4 (but I'll of course accept PRs if that proves not the case).

I won't add Python 3.4 compatibility to `setup.py` though, because I'm not sure I'll keep the project 3.4 compatible in the future. Python 3.5 is out and stable \o/
