### ISSUE TITLE
abrv.de vs abbrv.de

### ISSUE THREAD

**Issue by ThomasWaldmann** [rixx/abbr#2]
There seems to be some disagreement in the code / docs, do a global search & replace.

**Comment by rixx** [comment]
- The project is called `abbr`
- The README uses `abbrv.de` as exemplary domain
- One actual hosting domain is `abrv.de`

I'll change the README now that the service is actually running on a domain, but I don't see an actual problem here.

**Comment by ThomasWaldmann** [comment]
If meant as example, maybe follow the usual practice and use abbr.example.org?
