### ISSUE TITLE
use reduced alphabet for better legibility

### ISSUE THREAD

**Issue by ThomasWaldmann** [rixx/abbr#4]
one use case of url shorteners involves manually reading (and writing down) of a short URL.
for this it would be good to remove easily confusable char combinations from the default configuration.

Like:
- 1 and l
- 0 and o
- ...

**Comment by ThomasWaldmann** [comment]
Did you intentionally keep the old setting?
Like it is now, the change is not effective because overwritten in next line.

**Comment by rixx** [comment]
Oops.
